- DagConfiguration:
    file_dag_name: dag_gp_source_undivided
    dag_name: dag_gp_source_undivided
    description: Перенос данных неразграниченных объектов из postgresql в greenplum
    first_start: 2025-04-06-00-00-00
    owner: imedzhidli
    scheduler: 30 7 6 * *
    tags: source_undivided
