- DagConfiguration:
    file_dag_name: dag_ch_source_unowned
    dag_name: dag_ch_source_unowned
    description: Перенос данных о бесхозных объектах в ch_source_unowned
    first_start: 2025-03-23-00-00-00
    owner: imedzhidli
    scheduler: 0 8 1 * *
    tags: source_unowned, Бесхоз
