- DagConfiguration:
    file_dag_name: dag_gp_source_destructing
    dag_name: dag_gp_source_destructing
    description: Перенос ветхих объектов из postgresql в greenplum
    first_start: 2025-04-06-00-00-00
    owner: imedzhidli
    scheduler: 30 7 6 * *
    tags: Ветхие
