- DagConfiguration:
    file_dag_name: dag_ch_source_undivided
    dag_name: dag_ch_source_undivided
    description: Перенос данных неразграниченных объектов в ch_source_undivided
    first_start: 2025-03-23-00-00-00
    owner: imedzhidli
    scheduler: 0 8 1 * *
    tags: source_undivided
